version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: perenity-postgre-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: perenitydb
      POSTGRES_USER: perenity
      POSTGRES_PASSWORD: perenity
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
